apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
  labels: 
    app: todoapp
spec:
  containers:
  - name: busybox
    image: ikulyk404/busyboxplus:curl
    command: ["tail", "-f", "/dev/null"]
