apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  labels:
    app: todoapp
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: alinamoskovchuk18/todoapp:3.0.1
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 5
